### ISSUE TITLE
Percentuali di classi in quarantena

### ISSUE THREAD

**Issue by macteo** [napo/quaratene_covid_scuole_trentine#1]
Grazie per il lavoro.
Non riesco a capire il formato delle percentuali nelle colonne `percentuale_primaria` , `percentuale_secondaria_primo_grado` e `percentuale_secondaria_grado`.

Nella settimana del 24/01/2022 risultano 112 **sezioni** di scuola primaria in DaD.

<img width="1221" alt="Screenshot 2022-01-26 at 17 19 58" src="https://user-images.githubusercontent.com/587988/151202802-046b27ee-6ed6-4541-a9eb-0c1fce7e4d1d.png">

Come riportato sul sito vivoscuola.

<img width="1193" alt="screenshot_2022-01-26_at_17 05 59" src="https://user-images.githubusercontent.com/587988/151203630-2155ce47-e966-4706-9a25-872e32f51535.png">

Credo la percentuale sia stata calcolata dividendo le **sezioni** per il numero totale di **alunni**.
Ad esempio 112 sezioni in quarantena / 25862 alunni totali * 100 = 0.4%. 

Se così fosse si stanno dividendo sezioni per alunni.

`schools_trentino_covid['percentuale_primaria'] = schools_trentino_covid['scuola_primaria'].apply(lambda x: percentualeAlunniQuaratena(x,totale_studenti_primaria))`

**Comment by napo** [comment]
Grazie @macteo :)
Avevo caricato il file sbagliato<br/>
Ora i conti sono sulle percentuali di classi

Se fai un verifica e chiudi il commento mi fai un piacere

**Comment by macteo** [comment]
Perfetto ora mi sembra che le percentuali abbiano perfettamente senso. Grazie.
Dato interessante, la mia percezione basata sui figli mi portava ad immaginare percentuali ancora più elevate per le primarie.

Grazie, chiudo.
